(()=>{
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const norm=s=>(s||'').trim().toUpperCase().replace(/[^A-Z0-9]/g,'');
const map={RANGE:'range',TREND:'trend',PROTEIN:'protein','7DAYS':'7days',FOODNOISE:'foodnoise',EMOTION:'emotion',DOCTOR:'doctor','90DAYS':'90days',STRENGTH:'strength',MEAL:'meal',ALERT:'alert'};
const unlocked=new Set(JSON.parse(localStorage.getItem('nda-en-unlocked')||'[]'));
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderCards(){ $$('.tool-card').forEach(c=>c.classList.toggle('unlocked',unlocked.has(c.dataset.tool))); }
function activate(id){ const el=$('#tool-'+id); if(!el)return; $$('.tool').forEach(t=>t.classList.remove('active')); el.classList.add('active'); setTimeout(()=>el.scrollIntoView({behavior:'smooth',block:'start'}),50); }
function unlock(raw){ const code=norm(raw),id=map[code],msg=$('#code-msg'); if(!id){msg.textContent='Code not recognized. Please check the spelling in the book.';msg.className='code-msg err';return;} unlocked.add(id);localStorage.setItem('nda-en-unlocked',JSON.stringify([...unlocked]));renderCards();msg.textContent='Unlocked: '+code+'. The tool is open below.';msg.className='code-msg ok';activate(id); }
$('#code-form')?.addEventListener('submit',e=>{e.preventDefault();unlock($('#book-code').value)});
$$('.tool-card').forEach(c=>c.addEventListener('click',()=>{if(unlocked.has(c.dataset.tool))activate(c.dataset.tool);else{$('#book-code').focus();$('#code-msg').textContent='Enter the matching book code above first.';$('#code-msg').className='code-msg err';}}));
renderCards(); const qp=new URLSearchParams(location.search); if(qp.get('code'))unlock(qp.get('code'));

$('#range-form')?.addEventListener('submit',e=>{e.preventDefault();const base=+$('#range-base').value,width=+$('#range-width').value,buffer=+$('#range-buffer').value;if(!(base>0&&width>0&&buffer>0))return;const lo=base-width,hi=base+width,yhi=hi+buffer;$('#range-result').innerHTML=`<strong class="big">${lo.toFixed(1)}–${hi.toFixed(1)} kg</strong><b>Your defined maintenance range</b><p>Yellow zone above the range: ${hi.toFixed(1)}–${yhi.toFixed(1)} kg. Your self-defined red threshold begins at ${yhi.toFixed(1)} kg.</p><p><b>Yellow:</b> ${esc($('#range-yellow').value)||'no action set yet'}<br><b>Red:</b> ${esc($('#range-red').value)||'no action set yet'}</p><p class="tool-note">This visualizes your own plan. It does not define a medical threshold or recommend treatment.</p>`});

function parseWeights(text){return text.split(/\n+/).map(x=>x.trim()).filter(Boolean).map((line,i)=>{const parts=line.split(/[;\t]/);if(parts.length===1){let m=line.match(/(-?\d+(?:[.,]\d+)?)/);return m?{d:'Value '+(i+1),w:+m[1].replace(',','.')}:null}let w=+parts[parts.length-1].trim().replace(',','.');return isFinite(w)?{d:parts.slice(0,-1).join(' ').trim()||('Value '+(i+1)),w}:null}).filter(Boolean)}
function mean(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:NaN}
function drawTrend(vals){const c=$('#trend-canvas');const rect=c.getBoundingClientRect();c.width=Math.max(600,rect.width*2);c.height=Math.max(300,rect.height*2);const ctx=c.getContext('2d'),W=c.width,H=c.height,pad=56,d=vals.map(x=>x.w);ctx.clearRect(0,0,W,H);if(d.length<2)return;const min=Math.min(...d)-.6,max=Math.max(...d)+.6;ctx.strokeStyle='#d9dfdb';ctx.lineWidth=2;for(let i=0;i<5;i++){let y=pad+(H-2*pad)*i/4;ctx.beginPath();ctx.moveTo(pad,y);ctx.lineTo(W-pad,y);ctx.stroke()}const xy=(v,i)=>[pad+(W-2*pad)*i/(d.length-1),H-pad-(v-min)/(max-min)*(H-2*pad)];ctx.strokeStyle='#087d72';ctx.lineWidth=7;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();d.forEach((v,i)=>{let [x,y]=xy(v,i);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle='#ee6a2c';let [x,y]=xy(d[d.length-1],d.length-1);ctx.beginPath();ctx.arc(x,y,10,0,Math.PI*2);ctx.fill();}
$('#trend-form')?.addEventListener('submit',e=>{e.preventDefault();const vals=parseWeights($('#trend-values').value);if(vals.length<2){$('#trend-result').innerHTML='Please enter at least two weight values.';return}const last7=vals.slice(-7).map(x=>x.w),prev7=vals.slice(-14,-7).map(x=>x.w),avg=mean(last7),prev=mean(prev7),delta=isFinite(prev)?avg-prev:NaN;$('#trend-result').innerHTML=`<strong class="big">${avg.toFixed(2)} kg</strong><b>Average of the latest ${last7.length} values</b>${isFinite(delta)?`<p>Change versus the previous ${prev7.length} values: <b>${delta>=0?'+':''}${delta.toFixed(2)} kg</b>.</p>`:''}<p>Latest single value: ${vals.at(-1).w.toFixed(2)} kg. The average reduces daily noise; it is not a medical assessment.</p>`;drawTrend(vals)});

$('#protein-form')?.addEventListener('submit',e=>{e.preventDefault();const current=+$('#pro-current').value,target=+$('#pro-target').value,train=+$('#pro-train').value,kidney=$('#pro-kidney').checked;if(kidney){$('#pro-result').innerHTML='<b>No automatic calculation.</b><p>With known kidney disease or a medically prescribed protein restriction, the amount should be individualized with the treating clinician or dietitian.</p>';return}if(!(current>0&&target>0))return;const ref=current>target*1.25?target:Math.min(current,target*1.08);let lo=1.2,hi=1.4;if(train===1){lo=1.3;hi=1.6}else if(train===2){lo=1.4;hi=1.8}const a=Math.round(ref*lo),b=Math.round(ref*hi),mid=Math.round((a+b)/2);$('#pro-result').innerHTML=`<strong class="big">about ${a}–${b} g/day</strong><b>Pragmatic planning range</b><p>Calculation basis: ${ref.toFixed(1)} kg reference weight. This is not a medical target, but a practical planning range.</p><p>Example with 3 eating occasions: roughly ${Math.round(mid/3)} g per protein anchor. With 4: roughly ${Math.round(mid/4)} g.</p>`});

function make7(){const tb=$('#seven-body');if(!tb)return;for(let i=0;i<7;i++){const tr=document.createElement('tr');tr.innerHTML=`<td><input type="date" data-k="date"></td><td><input type="number" step="0.1" data-k="weight" placeholder="kg"></td><td><input type="number" data-k="steps" placeholder="e.g. 8000"></td><td><select data-k="training"><option value="0">no</option><option value="1">yes</option></select></td><td><input type="number" min="0" max="10" data-k="hunger" placeholder="0–10"></td><td><input type="number" min="0" max="10" data-k="noise" placeholder="0–10"></td><td><input type="number" step="1" data-k="kcal" placeholder="optional"></td>`;tb.appendChild(tr)}}make7();
$('#seven-analyze')?.addEventListener('click',()=>{const rows=$$('#seven-body tr').map(tr=>Object.fromEntries($$('[data-k]',tr).map(x=>[x.dataset.k,x.value])));const nums=k=>rows.map(r=>+r[k]).filter(v=>isFinite(v)&&v>0);const obs=[],steps=nums('steps'),h=nums('hunger'),n=nums('noise'),w=nums('weight'),kcal=nums('kcal');if(steps.length&&mean(steps)<6000)obs.push(`Your recorded steps average about ${Math.round(mean(steps))} per day.`);if(h.length&&mean(h)>=6)obs.push(`Average hunger is ${mean(h).toFixed(1)}/10 and stands out in this week's data.`);if(n.length&&mean(n)>=6)obs.push(`Food noise averages ${mean(n).toFixed(1)}/10 and is prominent this week.`);if(w.length>=4)obs.push(`The first and last recorded weights differ by ${w.at(-1)-w[0]>=0?'+':''}${(w.at(-1)-w[0]).toFixed(1)} kg. What matters is whether this persists.`);if(kcal.length>=4){const max=Math.max(...kcal),min=Math.min(...kcal);if(max-min>600)obs.push(`Recorded calorie intake varies by up to ${Math.round(max-min)} kcal between days.`)}if(!obs.length)obs.push('No single pattern clearly stands out in the available data. That is useful information too.');$('#seven-result').innerHTML='<b>Up to three observations</b><ol>'+obs.slice(0,3).map(x=>`<li>${x}</li>`).join('')+'</ol><p class="tool-note">Not a diagnosis and not a morality score. The purpose is to make patterns visible.</p>'});

$$('[data-fn]').forEach(x=>x.addEventListener('input',()=>{$('#fn-'+x.dataset.fn).textContent=x.value}));
$('#foodnoise-calc')?.addEventListener('click',()=>{const vals=$$('[data-fn]').map(x=>+x.value),score=vals.reduce((a,b)=>a+b,0),baseline=+(localStorage.getItem('nda-en-fn-baseline')||'NaN');$('#foodnoise-result').innerHTML=`<strong class="big">${score}/20</strong><b>Your personal comparison value</b><p>This is not a diagnosis and deliberately has no “good/bad” cutoff.</p>${isFinite(baseline)?`<p>Saved earlier comparison value: ${baseline}/20. Difference: ${score-baseline>=0?'+':''}${score-baseline} points.</p>`:''}<button class="btn btn-ghost" id="save-fn" type="button">Save as comparison value</button>`;$('#save-fn').onclick=()=>{localStorage.setItem('nda-en-fn-baseline',score);$('#save-fn').textContent='Saved — only in this browser'} });

const emoKey='nda-en-emotion';let emo=JSON.parse(localStorage.getItem(emoKey)||'[]');
function renderEmo(){const box=$('#emotion-list');if(!box)return;box.innerHTML=emo.length?emo.map((x,i)=>`<div class="emote-entry"><b>${esc(x.when||'Entry')}</b> · ${esc(x.trigger)} → ${esc(x.need)}<br><span class="dim">Short-term effect: ${esc(x.effect)}</span> <button class="btn btn-ghost" data-del-emo="${i}" type="button">delete</button></div>`).join(''):'<p class="dim">No entries stored in this browser yet.</p>';$$('[data-del-emo]').forEach(b=>b.onclick=()=>{emo.splice(+b.dataset.delEmo,1);localStorage.setItem(emoKey,JSON.stringify(emo));renderEmo()});const counts={};emo.forEach(x=>counts[x.trigger]=(counts[x.trigger]||0)+1);const top=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,3);$('#emotion-pattern').innerHTML=top.length?'<b>Most common triggers in your entries:</b> '+top.map(([k,v])=>`${esc(k)} (${v}×)`).join(', '):''}renderEmo();
$('#emotion-form')?.addEventListener('submit',e=>{e.preventDefault();emo.push({when:$('#emo-when').value,trigger:$('#emo-trigger').value,need:$('#emo-need').value,effect:$('#emo-effect').value});localStorage.setItem(emoKey,JSON.stringify(emo));e.target.reset();renderEmo()});

$('#doctor-build')?.addEventListener('click',()=>{const v=id=>esc($(id).value);$('#doctor-result').innerHTML=`<h3>Appointment preparation</h3><p><b>Weight:</b> current ${v('#doc-weight')||'–'} kg · starting ${v('#doc-start')||'–'} kg · trend: ${v('#doc-trend')||'–'}</p><p><b>Current treatment:</b> ${v('#doc-treatment')||'–'}</p><p><b>Hunger / food noise:</b> ${v('#doc-hunger')||'–'}</p><p><b>Side effects / notable changes:</b> ${v('#doc-side')||'–'}</p><p><b>Movement / strength training:</b> ${v('#doc-move')||'–'}</p><p><b>Main goal for this visit:</b> ${v('#doc-goal')||'–'}</p><p><b>My three questions:</b><br>1. ${v('#doc-q1')||'–'}<br>2. ${v('#doc-q2')||'–'}<br>3. ${v('#doc-q3')||'–'}</p><p class="tool-note">This page prepares a conversation; it does not decide dose changes, stopping, or treatment.</p>`});

const planKey='nda-en-90';let plan=JSON.parse(localStorage.getItem(planKey)||'{}');
function makeWeeks(){const box=$('#weeks');if(!box)return;const prompts=['Record your starting point','Observe the weight trend','Compare hunger deliberately','Keep movement consistent','Reduce unnecessary tracking','Review standard meals','Observe the weekend','Test restaurant / real life','Review a stressful week','Interpret travel / deviations','What can become simpler?','Write your personal maintenance manual'];box.innerHTML=prompts.map((p,i)=>`<div class="week-card"><label><input type="checkbox" data-week="${i}" ${plan[i]?.done?'checked':''}> Week ${i+1}</label><p>${p}</p><textarea data-week-note="${i}" placeholder="Short note">${esc(plan[i]?.note||'')}</textarea></div>`).join('');$$('[data-week]').forEach(x=>x.onchange=savePlan);$$('[data-week-note]').forEach(x=>x.oninput=savePlan)}function savePlan(){for(let i=0;i<12;i++){plan[i]={done:!!$('[data-week="'+i+'"]')?.checked,note:$('[data-week-note="'+i+'"]')?.value||''}}localStorage.setItem(planKey,JSON.stringify(plan));const done=Object.values(plan).filter(x=>x.done).length;$('#plan-progress').textContent=`${done}/12 weeks marked`;}makeWeeks();savePlan();

const meal={protein:['Chicken','Tofu','Skyr or Greek yogurt','Eggs','Fish','Lentils/beans'],carb:['Potatoes','Rice','Whole-grain bread','Oats','Couscous','Wrap'],produce:['Mixed vegetables','Salad','Berries/fruit','Roasted vegetables','Tomato/cucumber','Frozen vegetables'],flavor:['Yogurt-herb','Soy-ginger','Tomato-herb','Curry','Lemon-pepper','Paprika-garlic']};
function fillMeal(){for(const k of Object.keys(meal)){const s=$('#meal-'+k);s.innerHTML=meal[k].map(x=>`<option>${x}</option>`).join('')}}fillMeal();
function mealBuild(){const v=k=>$('#meal-'+k).value;$('#meal-result').innerHTML=`<strong class="big" style="font-size:1.5rem">${esc(v('protein'))} + ${esc(v('carb'))}</strong><p>${esc(v('produce'))} · ${esc(v('flavor'))}</p><p class="tool-note">This is a decision aid, not a universal portion or calorie prescription.</p>`}$('#meal-build')?.addEventListener('click',mealBuild);$('#meal-random')?.addEventListener('click',()=>{for(const k of Object.keys(meal)){const s=$('#meal-'+k);s.selectedIndex=Math.floor(Math.random()*s.options.length)}mealBuild()});

$('#alert-form')?.addEventListener('submit',e=>{e.preventDefault();const days=+$('#al-days').value,delta=+$('#al-delta').value,changed=$('#al-change').value==='yes',factors=$$('[name="al-factor"]:checked').map(x=>x.value);let steps=[];if(days<=5&&factors.length){steps=['First put short-term fluctuation in context rather than making a large change.','Observe another 3–7 days under similar conditions.','If the trend persists, open the 7-day review.']}else if(days<21){steps=['Look at the trend rather than single values.','Run the 7-day review: food, drinks, steps, training, hunger and food noise.','Choose one small predefined correction instead of several drastic changes at once.']}else{steps=['Document the longer-term trend clearly.','Review eating and movement patterns for 7–14 days.','If gain continues or hunger/food noise changes markedly, plan medical follow-up.']}if(changed)steps.unshift('Because medication changed, interpret this in a medical context — do not derive a dose decision from this tool.');if(delta>=5)steps.unshift('The recorded change is substantial. If it developed rapidly or without an obvious explanation, seek medical assessment.');$('#alert-result').innerHTML='<b>Your escalation plan</b><ol>'+steps.slice(0,4).map(x=>`<li>${x}</li>`).join('')+'</ol><p class="tool-note">This tool is not an emergency service. Seek medical help for severe acute symptoms, repeated vomiting, fainting/circulatory problems, or other urgent concerns.</p>'});

const bonus={
range:['More than one number','A range separates ordinary fluctuation from a pattern you deliberately want to watch.','Green does not mean perfect and yellow does not mean failure. Multiple comparable measurements matter more than one morning.','Do not rebuild the whole plan after a salty meal, travel or constipation.','Write your yellow and red actions while you are calm.'],
trend:['The signal behind the noise','Several values are usually more informative than today versus yesterday.','Direction over repeated measurements matters more than an outlier.','More weighing is useful only when more data creates less panic, not more.','Compare similar conditions when possible.'],
protein:['Protein without macro perfectionism','The planner should make meals easier, not turn the day into a math test.','Being near the range most days is often more practical than exact daily targets.','Protein does not replace vegetables, sufficient energy or ordinary food.','Build three or four reliable protein anchors first.'],
'7days':['Seven days as troubleshooting','The review forces you to collect data before reacting.','Look for patterns across steps, hunger, weekends, training and portions.','One week is short: use it for hypotheses, not definitive diagnoses.','Change one or two levers after the review, not everything at once.'],
foodnoise:['Your own trend matters most','Food noise is not an official diagnostic test. Its value is comparison with yourself.','A higher score can be a signal to look closer; it does not tell you why something changed.','Not every thought about food is a problem.','Save occasional comparison points after meaningful changes in routine, stress or treatment.'],
emotion:['From trigger to usable plan','Patterns are easier to see when you record what happened immediately before eating.','Repeated triggers matter more than one episode.','The map does not prove that eating is “psychological.” Hunger and emotion can coexist.','Create one small five-minute alternative for your most common trigger.'],
doctor:['Bring the pattern, not a self-diagnosis','Appointments are easier when trend, treatment, appetite, symptoms and questions fit on one page.','This is an agenda, not a medical letter.','Do not try to diagnose yourself before the appointment.','Put your most important question first.'],
'90days':['Twelve weeks, not forever','A 90-day plan makes the transition manageable.','Good and difficult weeks both provide useful information.','Missing a week does not mean starting over.','Every three weeks, write one sentence about what has become automatic.'],
strength:['Progression without a fitness project','Two solid sessions each week can beat a perfect plan that disappears after three weeks.','Early progress means consistency, then cleaner reps, more reps or slightly more load.','Soreness is not a quality score.','Keep the same basic exercises for several weeks so progress is visible.'],
meal:['Standards beat endless decisions','A few repeatable meals reduce mental load, especially during stressful periods.','Adjust the combinations to taste, hunger and portion needs.','A standard meal is a fallback, not an obligation.','Define two breakfasts, two quick main meals and one emergency option.'],
alert:['A plan for the moment when panic helps least','A rising trend can trigger an urge to change everything at once. The point of a plan is to slow that reflex.','Duration, size of change and short-term factors help separate observation from action.','A radical counterattack can turn a small deviation into another all-or-nothing system.','Write down what you observe first, what you change second, and when you ask for medical help.']
};
Object.entries(bonus).forEach(([id,b])=>{const tool=$('#tool-'+id);if(!tool)return;const s=document.createElement('section');s.className='bonus-hub';s.innerHTML=`<div class="bonus-head"><span class="tag">Book-code bonus</span><h3>${b[0]}</h3><p>The tool above stays intentionally compact. This is the context around it.</p></div><div class="bonus-grid"><article><span>Why it helps</span><p>${b[1]}</p></article><article><span>How to read it</span><p>${b[2]}</p></article><article><span>Common trap</span><p>${b[3]}</p></article><article class="bonus-hint"><span>Practical hint</span><p>${b[4]}</p></article></div>`;tool.appendChild(s)});
})();